name: infrastructure-setup

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]

  workflow_dispatch:
    inputs:
      AWS_REGION:
        description: region to use to create infrastructure
        required: true
        default: "ap-southeast-2"
      ENV:
        description: name of environment
        required: true
        default: "dev"
      GROUP_NAME:
        description: name of group
        required: true
        default: "__group__"
      AZ_COUNT:
        description: number of availability zones to use
        required: true
        default: "__az_count__"

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ ((github.event.inputs.AWS_REGION != '') && github.event.inputs.AWS_REGION) || 'ap-southeast-2' }}
      ENV_NAME: ${{ ((github.event.inputs.ENV != '') && github.event.inputs.ENV) || 'dev' }}
      GROUP_NAME: ${{ ((github.event.inputs.GROUP_NAME != '') && github.event.inputs.GROUP_NAME) || '__group__' }}
      AZ_COUNT: ${{ ((github.event.inputs.AZ_COUNT != '') && github.event.inputs.AZ_COUNT) || '__az_count__' }}
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Verify terraform
        run: terraform --version
        working-directory: ".terraform"

      - name: Configure AWS credential
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Init Terraform
        id: terraform-init
        run: terraform init
        working-directory: ".terraform"

      - name: Create workspace
        run: terraform workspace select ${{ env.AWS_REGION }}-${{ env.GROUP_NAME }}-${{ env.ENV_NAME }}-${{ env.AZ_COUNT }} || terraform workspace new ${{ env.AWS_REGION }}-${{ env.GROUP_NAME }}-${{ env.ENV_NAME }}-${{ env.AZ_COUNT }}
        working-directory: ".terraform"

      - name: Apply Terraform
        id: terraform-apply
        run: terraform apply -auto-approve -var="env=${{ env.ENV_NAME }}" -var="group=${{ env.GROUP_NAME }}" -var="aws_region=${{ env.AWS_REGION }}" -var="az_count=${{ env.AZ_COUNT }}"
        working-directory: ".terraform"
